### ISSUE TITLE
passing javascript functions inside configuration

### ISSUE THREAD

**Issue by scicco** [typpo/quickchart-ruby#4]
Hello,

I'm trying to make label display conditional, like in this [example](https://quickchart.io/documentation/chart-js/custom-pie-doughnut-chart-labels/), paragraph: 'Using the doughnutlabel plugin' in the bottom.

Is there any way to achieve that?

Here is what I've tried so far, unfortunately the chart still shows zeros as labels.

```
labels = ['Level 4', 'Level 3', 'Level 2', 'Level 1', 'Not Critical']
values = [0,0,0,3,27]
colors = ["#ff0100", "#ff7f7f", "#ffbfbf", "#ffe5e5", "#bfbfbf"]

chart_hash = {
  type: 'pie',
  data: {
    labels: labels,
    datasets: [
      {
        backgroundColor: colors,
        data: values
      }]
  },
  options: {
    legend: {
      position: "right",
      labels: {
        fontSize: 20
      }
    },
    plugins: {
      datalabels: {
        display: true,
        align: 'bottom',
        #backgroundColor: '#ccc',
        color: 'fff',
        borderRadius: 3,
        #HERE I TRY TO CONDITIONAL HIDE IT
        display: ->(context) {
          context.dataset.data[context.dataIndex] != 0
        },
        #HERE I TRY TO ALTER VALUE
        formatter: ->(val, ctx) {
          return val != 0 ? val : '';
        },
        font: {
          size: 20,
        }
      },
    }
  }
}

qc = QuickChart.new(chart_hash)
qc.get_url
```

This is the output: 

<img width="509" alt="Screenshot 2021-04-21 at 14 01 26" src="https://user-images.githubusercontent.com/943152/115550562-4888d880-a2aa-11eb-933f-b9cc4b20dd53.png">

Thank you in advance

**Comment by typpo** [comment]
You'll have to pass the configuration as a string containing valid Javascript, like in [this example](https://github.com/typpo/quickchart-ruby/blob/master/examples/simple_example_with_function.rb).  You can interpolate the values and colors variables in the string.  Let me know how that works for you :)

**Comment by arnoldtonderaimarunda** [comment]
> You'll have to pass the configuration as a string containing valid Javascript, like in [this example](https://github.com/typpo/quickchart-ruby/blob/master/examples/simple_example_with_function.rb). You can interpolate the values and colors variables in the string. Let me know how that works for you :)

Your solution not working for me. The => throws an unexpected error. 
I'm also trying to alter the data label to add a suffix "%" using the following code

```
def drawPieChart(type, title, labels, series, data, height, width, file)
    qc = QuickChart.new(
        {
            type: type,
            data: {
            datasets: [
                {
                data: data,
                backgroundColor: [
                    '#9FD1FF',
                    '#F5FFA2',
                    '#AAFFA2',
                    '#FFAEF7',
                    '#FF8B8B',
                    '#B3BAFE',
                    '#EBF0C1',
                    '#F4BAD4'
                ],
                label: series,
                },
            ],
            labels: labels,
            },
            options: {
                title: {
                display: true,
                text: title
                },
                plugins: {
                    datalabels: {
                        fontFamily: 'roboto',
                        fontStyle: 'bold',
                        formatter: -> (val) {
                            return val + '%';
                        },
                        
                    },
                },
            }
        },
        width: width, height: height, device_pixel_ratio: 2.0
    )
    qc.to_file(file)
end 
```
Chartjs documentation https://chartjs-plugin-datalabels.netlify.app/guide/formatting.html#data-transformation
provides the following example
```
formatter: function(value, context) {
  return context.dataIndex + ': ' + Math.round(value*100) + '%';
}

// label for data at index 0 with value 0.23: "0: 23%"
// label for data at index 1 with value 0.42: "1: 42%"
// ...
```

**Comment by typpo** [comment]
Hi @arnoldtonderaimarunda.  What version of Ruby are you running?  The high-level requirement is that you pass the config as a _string_.  If you convert your configuration to a string and pass it to `QuickChart.new`, you should be good.
